
# Site settings
title: Your awesome title
description: A starter site
baseurl: "" # folder where your site lives, e.g. /web1-sp
url: "http://localhost:8000" # the base hostname & protocol for your site, e.g. http://hostname.domain.com

# Build settings
markdown: kramdown

